services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    networks:
      - devsecops-net
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./scripts/grafana/provisioning:/etc/grafana/provisioning

networks:
  devsecops-net:
    external: false

volumes:
  grafana_storage:
