stages:
  - test
  - upload

variables:
  SAST_ANALYZER_IMAGE_PREFIX: "10.22.255.62:5002/adminuser/django-nv-import/sast-tools"
  DOCKER_AUTH_CONFIG: >-
    {
      "auths": {
        "10.22.255.62:5002": {
          "auth": "YWRtaW51c2VyOk15UzNjdXJlIVJvb3RAMjAyNg=="
        }
      }
    }

# ---------------- TEST 1 ----------------
semgrep-sast-1:
  stage: test
  image: $SAST_ANALYZER_IMAGE_PREFIX/semgrepp:latest
  artifacts:
    reports:
      sast: gl-sast-report-1.json
    paths:
      - gl-sast-report-1.json
    when: always
  script:
    - /analyzer run

upload-test-1:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: semgrep-sast-1
      artifacts: true
  script:
    - >
      curl -X POST "http://10.22.255.62:8080//api/v2/reimport-scan/"
      -H "Authorization: Token 41d2287be2dde87bbfae2242c34a050cfad0a5dd"
      -F "active=true"
      -F "verified=true"
      -F "scan_type=GitLab SAST Report"
      -F "minimum_severity=High"
      -F "product_name=django-nv-import-1775733304"
      -F "engagement_name=CI-CD Scan 1775733304"
      -F "test_title=Semgrep Scan - Test 1"
      -F "auto_create_context=true"
      -F "file=@gl-sast-report-1.json"

# ---------------- TEST 2 ----------------
semgrep-sast-2:
  stage: test
  image: $SAST_ANALYZER_IMAGE_PREFIX/semgrepp:latest
  artifacts:
    reports:
      sast: gl-sast-report-2.json
    paths:
      - gl-sast-report-2.json
    when: always
  script:
    - /analyzer run

upload-test-2:
  stage: upload
  image: curlimages/curl:latest
  needs:
    - job: semgrep-sast-2
      artifacts: true
  script:
    - >
      curl -X POST "http://10.22.255.62:8080//api/v2/reimport-scan/"
      -H "Authorization: Token 41d2287be2dde87bbfae2242c34a050cfad0a5dd"
      -F "active=true"
      -F "verified=true"
      -F "scan_type=GitLab SAST Report"
      -F "minimum_severity=High"
      -F "product_name=django-nv-import-1775733304"
      -F "engagement_name=CI-CD Scan 1775733304"
      -F "test_title=Semgrep Scan - Test 2"
      -F "auto_create_context=true"
      -F "file=@gl-sast-report-2.json"
