include:
  - path: ./scripts/vault/vault.yml
    project_directory: .
    env_file: .env        
  - path: ./scripts/gitlab/gitlab.yml
    project_directory: .
    env_file: .env
  - path: ./scripts/grafana/grafana.yml  
    project_directory: .
    env_file: .env

networks:
  devsecops-net:
    name: devsecops-net
    driver: bridge

volumes:
  gitlab_data:
  gitlab_runner_data:
  grafana_data:
