apiVersion: 1

datasources:
  - name: DefectDojo_Postgres
    type: postgres
    access: proxy
    url: django-defectdojo-postgres-1:5432
    database: defectdojo
    user: defectdojo
    isDefault: true
    secureJsonData:
      password: defectdojo
    jsonData:
      sslmode: 'disable'
      postgresVersion: 15
    editable: true
